blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ å‚ä¸è®¨è®º
    url: https://github.com/ä¸€ç”Ÿä¸€èŠ¯china/ä¸€ç”Ÿä¸€èŠ¯å¼€æºé¡¹ç›®ç®¡ç†å§”å‘˜ä¼š/discussions
    about: æ¬¢è¿å‚ä¸åˆ° ä¸€ç”Ÿä¸€èŠ¯ ç¤¾åŒºçš„è®¨è®º
